project_index:
    path:     /
    defaults: { _controller: "ProjectBundle:Project:index" }
project_new:
    path:     /new
    defaults: { _controller: "ProjectBundle:Project:new" }
project_user:
    path:     /add-user/{id}
    defaults: { _controller: "ProjectBundle:Project:addUser" }

project_edit:
    path:     /edit/{id}
    defaults: { _controller: "ProjectBundle:Project:edit" }
project_delete:
    path:     /delete/{id}
    defaults: { _controller: "ProjectBundle:Project:delete" }
project_fiche:
    path:     /index/{id}
    defaults: { _controller: "ProjectBundle:Project:fiche" }